WINDOW_NAME = 'Microsoft Minesweeper'
WINDOW_POSITION_START = (9,10)

SENIOR_MINE_TOTAL = 99
MIDDLE_MINE_TOTAL = 40

SENIOR_BOARD_HEIGHT = 16
SENIOR_BOARD_WIDTH = 30 

MIDDLE_BOARD_HEIGHT = 16
MIDDLE_BOARD_WIDTH = 16


MIDDLE_WINDOW_HEIGHT = 768
MIDDLE_WINDOW_WIDTH = 768

SENIOR_WINDOW_HEIGHT = 715
SENIOR_WINDOW_WIDTH = 1344

SENIOR_PIXEL_GAPX = 45
SENIOR_PIXEL_GAPY = 45

MIDDLE_PIXEL_GAPX = 48.5
MIDDLE_PIXEL_GAPY = 48.5

SENIOR_CELL_SIZE = 22
MIDDLE_CELL_SIZE = 25

MIDDLE_SHOOT_POSITION = (410, 108)
SENIOR_SHOOT_POSITION = (123,138)

CF = {
    'unknown':[(100,130),(160,220),(200,256)],
    'flag':[(210,256),(160,230),(40,92)],
    '1':[(10,40),(140,200),(170,240)],
    '2':[(90,120),(120,160),(20,60)],
    '3':[(180,240),(30,60),(80,120)],
    '4':[(20,60),(60,91),(110,170)],
    '5':[(120,200),(30,60),(30,60)],
    '6':[(40,70),(130,170),(70,90)]
    }

BLOCKS = {
    'unknown':-2,
    'flag':-1,
    'white':0,
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6
    }

CNT_THRESHOLD = 5

MODE_MIDDLE = {
    'PIXEL_GAPX':MIDDLE_PIXEL_GAPX, 
    'PIXEL_GAPY':MIDDLE_PIXEL_GAPY, 
    'CF':CF, 
    'BLOCKS':BLOCKS, 
    'CNT_THRESHOLD':CNT_THRESHOLD, 
    'WINDOW_POSITION_START':WINDOW_POSITION_START, 
    'CELL_SIZE':MIDDLE_CELL_SIZE,
    'BOARD_HEIGHT':MIDDLE_BOARD_HEIGHT,
    'BOARD_WIDTH':MIDDLE_BOARD_WIDTH,
    'WINDOW_HEIGHT':MIDDLE_WINDOW_HEIGHT,
    'WINDOW_WIDTH':MIDDLE_WINDOW_WIDTH,
    'SHOOT_POSITION':MIDDLE_SHOOT_POSITION,
    'MINE_TOTAL':MIDDLE_MINE_TOTAL,
}

MODE_SENIOR = {
    'PIXEL_GAPX':SENIOR_PIXEL_GAPX, 
    'PIXEL_GAPY':SENIOR_PIXEL_GAPY, 
    'CF':CF, 
    'BLOCKS':BLOCKS, 
    'CNT_THRESHOLD':CNT_THRESHOLD, 
    'WINDOW_POSITION_START':WINDOW_POSITION_START, 
    'CELL_SIZE':SENIOR_CELL_SIZE,
    'BOARD_HEIGHT':SENIOR_BOARD_HEIGHT,
    'BOARD_WIDTH':SENIOR_BOARD_WIDTH ,
    'WINDOW_HEIGHT':SENIOR_WINDOW_HEIGHT,
    'WINDOW_WIDTH':SENIOR_WINDOW_WIDTH,
    'SHOOT_POSITION':SENIOR_SHOOT_POSITION,
    'MINE_TOTAL':SENIOR_MINE_TOTAL
}
